function [gridCellInteriorInitLabels,gridCellFaceInitLabels] ...
                        = getInitLabels(imageStack3D_label,sizeR,sizeC,...
                        numZ,gridResX,gridResY,gridResZ,thresh_mem)
                    
                    
                    
[gridCIDs_sectionIDs_rootPixIDsRel,gridCellInteriorInitLabels,...
    cellInteriorRGBLabelsAll,numCellsY,numCellsX]...
            = createInitLabelsForGridCells...
            (imageStack3D_label,sizeR,sizeC,numZ,gridResX,gridResY,gridResZ,...
            thresh_mem);
        
gridCellFaceInitLabels = getCellFaceInitLabels...
                    (cellInteriorRGBLabelsAll,numZ,...
                    numCellsX,numCellsY);