neuronIDsForGridCells ...
            = getNeuronIDsForGridCells(x,numCellsY,numCellsX,numZ);
        
savePath = '/home/thanuja/Dropbox/data/3D_Grid_ILP/trainingData/Results_ILPseg/20140318_1/RGB_cc';

visualizeNeurons(neuronIDsForGridCells,numCellsY,...
                    numCellsX,numZ,gridResY,gridResX,rootPixels,...
                    savePath);